Fixed bugs

diff --git a/src/cromha-manager b/src/cromha-manager
--- a/src/cromha-manager
+++ b/src/cromha-manager
@@ -444,12 +444,16 @@ if [ "$option" == "sys-upgrade" ] || [ "$option" == "system-upgrade" ]; then
       sleep 3
       echo -e "${C5}Checking current Linux distribution...${Color_Off}"
       echo " "
+      if [ "$user_distro" == "none" ]; then
+            echo -e "${B1}ERROR: Sorry but it seems that you didn't specified any distro in your config file located in $HOME/cromha-manager-config.yaml. Please use cromha-manager config to specify it they try again $progress_bar_error"
+            echo " "
+            echo -e "${C5}Aborting current process..."
+            sleep .5
+            exit 1
+      fi
       echo -e "${C3}Is it right that you are on the distro '$user_distro'? (y/n)${Color_Off}"
       read answer
       echo -e " "
-      if [ "$user_distro" == "" ]; then
-            echo -e "${B1}ERROR: Sorry but it seems that you didn't specified any distro in your config file located in $HOME/cromha-manager-config.yaml. Please use cromha-manager config to specify it they try again $progress_bar_error"
-      fi
       if [ "$user_distro" == "fedora" ] && [ "$answer" == "y" ]; then
             current_fedora_ver=$(awk -F= '$1=="VERSION_ID" { print $2 ;}' /etc/os-release)
             new_fedora_ver=$(echo -e $(( "$current_fedora_ver" + 1 )))
