Did changes

diff --git a/src/cromha-manager-ctl b/src/cromha-manager-ctl
--- a/src/cromha-manager-ctl
+++ b/src/cromha-manager-ctl
@@ -122,6 +122,21 @@ function Timer () {
       echo 0
 }
 
+function CheckNetwork () {
+      echo -e "${C5}Checking network connection...${Color_Off}"
+      wget --spider --quiet http://google.com
+      if [ "$?" != 0 ]; then
+            sleep 3
+            echo ""
+            echo -e "${B1}ERROR: Your computer is not connected to any network, please make sure it is connected to the internet${Color_Off}"
+            sleep 3
+            echo ""
+            echo -e "${C5}Aborting current process...${Color_Off}"
+            sleep 1
+            exit
+      fi
+}
+
 # YAML parser
 function parse_yaml {
       local prefix=$2
@@ -261,8 +276,8 @@ fi
 
 if [ "$option" == "upgrade" ] || [ "$option" == "update" ]; then
       echo -e " "
-      echo -e "${C5} Checking Internet Connection..."
-      sleep 1
+      CheckNetwork
+      sleep 3
       echo -e "${C5} Checking GitHub Repo..."
       sleep 2
       echo -e "${C5} Cloning GitHub Repo into $HOME/Cromha-manager (default path)..."
