Did changes

diff --git a/src/cromha-manager b/src/cromha-manager
--- a/src/cromha-manager
+++ b/src/cromha-manager
@@ -122,6 +122,18 @@ function Timer () {
       echo 0
 }
 
+function CheckNetwork () {
+      echo -e "${C5}Checking network connection...${Color_Off}"
+      wget --spider --quiet http://google.com
+      if [ "$?" != 0 ]; then
+            echo ""
+            echo -e "${B1}ERROR: Your computer is not connected to any network, please make sure it is connected to the internet${Color_Off}"
+            echo ""
+            echo -e "${C5}Aborting current process...${Color_Off}"
+            exit
+      fi
+}
+
 # YAML parser
 function parse_yaml {
       local prefix=$2
@@ -298,6 +310,8 @@ if [ "$option" == "autoremove" ]; then
 fi
 
 if [ "$option" == "upgrade" ] || [ "$option" == "update" ]; then
+      CheckNetwork
+      sleep 3
       echo -e "${C5}Checking for package managers updates...${Color_Off}"
       sleep 3
       echo -e "${C5}Updating different package managers...${Color_Off}"
@@ -356,9 +370,11 @@ if [ "$option" == "upgrade" ] || [ "$option" == "update" ]; then
 fi
 
 if [ "$option" == "upgrade-all" ] || [ "$option" == "update-all" ]; then
+      CheckNetwork
+      sleep 3
       echo -e "${C5}Checking for package managers updates...${Color_Off}"
       sleep 3
-      echo -e "${C5}Trying to updating all package managers...${Color_Off}"
+      echo -e "${C5}Trying to update all package managers...${Color_Off}"
       echo -e " "
       echo -e "[Updating Flatpak Packages]"
       sudo flatpak update -y >&- 2>&- & PIDFLATPAK1=$!
@@ -401,6 +417,8 @@ fi
 if [ "$option" == "sys-upgrade" ] || [ "$option" == "system-upgrade" ]; then
       echo -e "${C6}It is highly recommended to make a backup of your system before upgrading to a new distribution release"
       echo -e ""
+      CheckNetwork
+      sleep 3
       echo -e "${C5}Checking current Linux distribution...${Color_Off}"
       echo " "
       echo -e "${C3}Is it right that you are on the distro '$user_distro'? (y/n)${Color_Off}"
@@ -413,6 +431,8 @@ if [ "$option" == "sys-upgrade" ] || [ "$option" == "system-upgrade" ]; then
             echo -e "${B6}System upgrade will begin in $wait_time seconds${Color_Off}"
             notify-send "System upgrade will begin in $wait_time seconds"
             Timer
+            CheckNetwork
+            sleep 3
             echo -e "${C5}Installing dnf system-upgrade plugin if not installed...${Color_Off}"
             sudo dnf install dnf-plugin-system-upgrade -y >&- 2>&- & PID1=$!
             echo "[Installing system-upgrade dnf plugin]"
@@ -445,6 +465,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid flatpak package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from flathub repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From Flatpak]"
@@ -463,6 +485,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid snapcraft package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleeep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from snapcraft repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From Snapcraft]"
@@ -481,6 +505,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid yum package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from yum repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From Yum]"
@@ -499,6 +525,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid cargo package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from cargo repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From Cargo]"
@@ -517,6 +545,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid dnf package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from dnf repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From Dnf]"
@@ -535,6 +565,8 @@ if [ "$option" == "package-upgrade" ] || [ "$option" == "package-update" ]; then
                   echo -e "${C3}Please enter a valid apt package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying upgrading package '$package_install_name' from apt repo...${Color_Off}"
                   echo " "
                   echo "[Upgrading From APT]"
@@ -794,6 +826,8 @@ if [ "$option" == "search" ] || [ "$option" == "find" ]; then
       echo -e "${C3}Enter package name:${Color_Off}"
       read package_find_name
       echo -e " "
+      CheckNetwork
+      sleep 3
       echo -e "${C5}Updating package managers...${Color_Off}"
       sleep 1
       echo -e "${C5}Searching for matches..."${Color_Off}
@@ -868,6 +902,9 @@ if [ "$option" == "search" ] || [ "$option" == "find" ]; then
 fi
 
 if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
+      CheckNetwork
+      sleep 3
+      echo ""
       echo -e "${C3}Please select a valid package manager:${Color_Off}"
       read answer
       echo " "
@@ -879,6 +916,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$flatpak" == True ]; then
                   echo -e "${C3}Please enter a valid flatpak package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -900,6 +938,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$snap" == True ]; then
                   echo -e "${C3}Please enter a valid snap package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -921,6 +960,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$yum" == True ]; then
                   echo -e "${C3}Please enter a valid yum package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -951,6 +991,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$dnf" == True ]; then
                   echo -e "${C3}Please enter a valid dnf package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -972,6 +1013,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$apt" == True ]; then
                   echo -e "${C3}Please enter a valid apt package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -993,6 +1035,7 @@ if [ "$option" == "info" ] || [ "$option" == "get-info" ]; then
             if [ "$zypp" == True ]; then
                   echo -e "${C3}Please enter a valid apt package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_info_name
+                  echo ""
                   echo -e "[Getting Info]"
                   ProgressBarFast & PID1=$!
                   echo "[$package_info_name PACKAGE INFO]" >> $HOME/cromha-manager-info.tmp
@@ -1021,6 +1064,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid flatpak package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from flathub repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Flatpak]"
@@ -1039,6 +1084,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid snapcraft package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from snapcraft repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Snapcraft]"
@@ -1057,6 +1104,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid yum package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from yum repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Yum]"
@@ -1075,6 +1124,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid cargo package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from cargo repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Cargo]"
@@ -1093,6 +1144,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid dnf package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from dnf repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Dnf]"
@@ -1111,6 +1164,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid apt package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from apt repo...${Color_Off}"
                   echo " "
                   echo "[Installing From APT]"
@@ -1129,6 +1184,8 @@ if [ "$option" == "install" ] || [ "$option" == "add" ]; then
                   echo -e "${C3}Please enter a valid zypp package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying installing package '$package_install_name' from zypp repo...${Color_Off}"
                   echo " "
                   echo "[Installing From Zypp]"
@@ -1285,6 +1342,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid flatpak package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from flathub repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Flatpak]"
@@ -1303,6 +1362,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid snapcraft package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from snapcraft repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Snapcraft]"
@@ -1323,6 +1384,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid yum package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from yum repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Yum]"
@@ -1341,6 +1404,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid cargo package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from cargo repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Cargo]"
@@ -1361,6 +1426,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid dnf package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from dnf repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Dnf]"
@@ -1379,6 +1446,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid apt package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from apt repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From APT]"
@@ -1397,6 +1466,8 @@ if [ "$option" == "reinstall" ]; then
                   echo -e "${C3}Please enter a valid zypp package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying reinstalling package '$package_install_name' from zypp repo...${Color_Off}"
                   echo " "
                   echo "[Reinstalling From Zypp]"
@@ -1445,6 +1516,8 @@ if [ "$option" == "downgrade" ]; then
                   echo -e "${C3}Please enter a valid yum package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying downgrading package '$package_install_name' from yum repo...${Color_Off}"
                   echo " "
                   echo "[Downgrading From Yum]"
@@ -1473,6 +1546,8 @@ if [ "$option" == "downgrade" ]; then
                   echo -e "${C3}Please enter a valid dnf package id (Use cromha-manager find/search to find an id):${Color_Off}"
                   read package_install_name
                   echo " "
+                  CheckNetwork
+                  sleep 3
                   echo -e "${C5}Trying downgrading package '$package_install_name' from dnf repo...${Color_Off}"
                   echo " "
                   echo "[Downgrading From Dnf]"
